#!/usr/bin/env fish

set -l WARMUP 10
set -l QUERY "main"
set -l -a FILES "src/main.rs"
set -l -a FILES "src/main.rs"
set -l -a FILES "src/main.rs"
set -l -a FILES "src/main.rs"
set -l -a FILES "src/main.rs"
set -l -a FILES "src/main.rs"

# Build tools
cargo build --release --bin 'minigrep'
cargo build --release --bin 'milligrep'
cargo build --release --bin 'ugrep'

# List of tools to test
set -l -a TOOLS "./target/release/minigrep"
set -l -a TOOLS "./target/release/milligrep"
set -l -a TOOLS "./target/release/ugrep"
# System tools
set -l -a TOOLS "$(which grep) --color"
set -l -a TOOLS "$(which grep)"

for tool in $TOOLS
    echo "Testing '$tool'"
    hyperfine --warmup $WARMUP --shell 'none' "$tool $QUERY $FILES"
end
